ccflags-y += -Idrivers/soc/hsoc/include

obj-$(CONFIG_PRODUCT_DEBUGINFO) 	  += hs_debuginfo.o
hs_debuginfo-y := debuginfo_main.o

obj-$(CONFIG_BOOTLOADER_LOG)  	+= bootloader_log.o
obj-$(CONFIG_DEBUG_BOOT_TIME)  += boottime_stats.o
